dist: trusty

language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run ci

after_success:
  - cat coverage/lcov.info | coveralls
