dist: trusty

language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run lint
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - npm run e2e
  - npm run build

after_success:
  - cat coverage/lcov.info | coveralls
