dist: trusty

language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run lint
  - npm run test:ci
  - npm run build
